# Generated by Django 3.2.7 on 2021-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('car_price', models.FloatField()),
                ('car_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
